blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/RiceKrisBs/pokemon-lorem-ipsum/discussions
    about: Please ask and answer questions or start discussions here
  - name: Documentation
    url: https://github.com/RiceKrisBs/pokemon-lorem-ipsum#readme
    about: Check the README for usage information
